### ISSUE TITLE
minushalf run-atomic Error

### ISSUE THREAD

**Issue by sajidurehman** [hentt30/minushalf#37]
Hi Developer,
                     In first step i have created the INP file by executing **minushalf create-input** command. In next step when trying to execute **minushalf run-atomic** command following files are not generated

VTOTAL.ae, OUT, AECHARGE, CHARGE, RHO, AEWFNR0, AEWFNR3 ....etc.

Just appeared this message : 
2022-03-25 17:13:18.299 | INFO     | minushalf.commands.run_atomic_program:run_atomic:51 - Run atomic program

Could you please let me know how to fix this issue. I will be very thankful to you.

Looking forward to hear you

Best Regards
Sajid

**Comment by hentt30** [comment]
Hi Sajid

Could you tell me which operating system you are using and give me the INP file generated by the create-input command?

**Comment by sajidurehman** [comment]
> Hi Sajid
> 
> Could you tell me which operating system you are using and give me the INP file generated by the create-input command?

**Comment by sajidurehman** [comment]
Hi Henrique,
                   Thank you for reply. I am using Ubuntu 18.04.4 LTS 64bit.
following data is generated by create-input command 

   ae      Si
 n=Si c=pb
       0.0       0.0       0.0       0.0       0.0       0.0
    3    4
    3    0     2.000     0.000
    3    1     2.000     0.000
    3    2     0.000     0.000
    4    3     0.000     0.000
100 maxit

**Comment by sajidurehman** [comment]
Sorry I mistakenly closed the issue. I don't know how to reopen again.

**Comment by sajidurehman** [comment]
Hi Henrique,
                    I have resolved the issue. Actually, It was due to pip old version. I have updated the pip to latest version now **minushalf run-atomic** working smoothly and generated the all required files.

Sorry for inconvenience.  Thank you for understanding.
